In [1]:
import pandas as pd

# create dataset for Corona Virus year March 2020 - Feb 2021

In [2]:
feb_df = pd.read_csv("Data/202102.csv")
feb_df.shape

(4737, 15)

In [3]:
feb_df["Year"] = 2021

In [4]:
feb_df["Month"] = 2

In [5]:
feb_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Year,Month
0,588,42:51.9,52:40.4,3185,City Hall,40.717733,-74.043845,3269,Brunswick & 6th,40.726012,-74.050389,42596,Subscriber,1986,2,2021,2
1,454,29:25.6,37:00.1,3679,Bergen Ave,40.722104,-74.071455,3195,Sip Ave,40.730897,-74.063913,30360,Subscriber,1963,1,2021,2
2,1893,27:44.7,59:18.6,3211,Newark Ave,40.721525,-74.046305,3267,Morris Canal,40.712419,-74.038526,47254,Subscriber,1961,2,2021,2
3,874,42:55.8,57:30.1,3267,Morris Canal,40.712419,-74.038526,3199,Newport Pkwy,40.728745,-74.032108,48753,Subscriber,1991,1,2021,2
4,266,26:47.3,31:13.7,3276,Marin Light Rail,40.714584,-74.042817,3205,JC Medical Center,40.716540,-74.049638,32526,Subscriber,1987,1,2021,2

In [6]:
jan_df = pd.read_csv("Data/202101.csv")
jan_df.shape

(11624, 15)

In [7]:
jan_df["Year"] = 2021
jan_df["Month"] = 1

In [8]:
master_df = pd.concat([feb_df,jan_df])
master_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Year,Month
0,588,42:51.9,52:40.4,3185,City Hall,40.717733,-74.043845,3269,Brunswick & 6th,40.726012,-74.050389,42596,Subscriber,1986,2,2021,2
1,454,29:25.6,37:00.1,3679,Bergen Ave,40.722104,-74.071455,3195,Sip Ave,40.730897,-74.063913,30360,Subscriber,1963,1,2021,2
2,1893,27:44.7,59:18.6,3211,Newark Ave,40.721525,-74.046305,3267,Morris Canal,40.712419,-74.038526,47254,Subscriber,1961,2,2021,2
3,874,42:55.8,57:30.1,3267,Morris Canal,40.712419,-74.038526,3199,Newport Pkwy,40.728745,-74.032108,48753,Subscriber,1991,1,2021,2
4,266,26:47.3,31:13.7,3276,Marin Light Rail,40.714584,-74.042817,3205,JC Medical Center,40.716540,-74.049638,32526,Subscriber,1987,1,2021,2

In [9]:
master_df.shape

(16361, 17)

In [10]:
dec_df = pd.read_csv("Data/202012.csv")
dec_df.shape

(11694, 15)

In [11]:
def add_date(df, year, month):
    df["Year"] = year;
    df["Month"] = month;
    df.shape;
    return df

In [12]:
dec_df_extended = add_date(dec_df,2020,12)

In [13]:
dec_df_extended.shape

(11694, 17)

In [14]:
dec_df_extended.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Year,Month
0,146,02:50.1,05:16.2,3202,Newport PATH,40.727224,-74.033759,3199,Newport Pkwy,40.728745,-74.032108,42308,Subscriber,1989,2,2020,12
1,572,11:57.4,21:30.3,3640,Journal Square,40.733670,-74.062500,3280,Astor Place,40.719282,-74.071262,18568,Subscriber,1997,2,2020,12
2,387,14:49.4,21:16.9,3640,Journal Square,40.733670,-74.062500,3194,McGinley Square,40.725340,-74.067622,44543,Subscriber,1960,1,2020,12
3,188,45:06.4,48:14.4,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,43098,Subscriber,1998,1,2020,12
4,594,17:17.0,27:11.9,3212,Christ Hospital,40.734786,-74.050444,3209,Brunswick St,40.724176,-74.050656,44723,Subscriber,1988,1,2020,12

In [15]:
df = pd.read_csv("Data/202011.csv")
df_extended = add_date(df,2020,11)
df_extended.shape
df_extended.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Year,Month
0,756,11:32.6,24:09.6,3275,Columbus Drive,40.718355,-74.038914,3225,Baldwin at Montgomery,40.723659,-74.064194,42436,Subscriber,1984,1,2020,11
1,584,14:20.5,24:04.8,3681,Grand St,40.715178,-74.037683,3209,Brunswick St,40.724176,-74.050656,46532,Customer,1969,0,2020,11
2,403,22:55.9,29:39.1,3203,Hamilton Park,40.727596,-74.044247,3483,Montgomery St,40.719420,-74.050990,35139,Subscriber,1980,1,2020,11
3,498,41:37.4,49:55.7,3268,Lafayette Park,40.713464,-74.062859,3213,Van Vorst Park,40.718489,-74.047727,46539,Customer,1969,0,2020,11
4,151,53:21.2,55:52.8,3185,City Hall,40.717733,-74.043845,3276,Marin Light Rail,40.714584,-74.042817,44388,Subscriber,1986,1,2020,11

In [16]:
df_extended.shape

(21275, 17)

In [17]:
master_df = pd.concat([master_df,dec_df_extended,df_extended])
master_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Year,Month
0,588,42:51.9,52:40.4,3185,City Hall,40.717733,-74.043845,3269,Brunswick & 6th,40.726012,-74.050389,42596,Subscriber,1986,2,2021,2
1,454,29:25.6,37:00.1,3679,Bergen Ave,40.722104,-74.071455,3195,Sip Ave,40.730897,-74.063913,30360,Subscriber,1963,1,2021,2
2,1893,27:44.7,59:18.6,3211,Newark Ave,40.721525,-74.046305,3267,Morris Canal,40.712419,-74.038526,47254,Subscriber,1961,2,2021,2
3,874,42:55.8,57:30.1,3267,Morris Canal,40.712419,-74.038526,3199,Newport Pkwy,40.728745,-74.032108,48753,Subscriber,1991,1,2021,2
4,266,26:47.3,31:13.7,3276,Marin Light Rail,40.714584,-74.042817,3205,JC Medical Center,40.716540,-74.049638,32526,Subscriber,1987,1,2021,2

In [18]:
master_df.tail()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Year,Month
21270,849,08:40.2,22:50.1,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,44742,Subscriber,1996,2,2020,11
21271,370,09:27.0,15:37.3,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,17450,Subscriber,1999,1,2020,11
21272,341,37:53.1,43:34.1,3187,Warren St,40.721124,-74.038051,3202,Newport PATH,40.727224,-74.033759,42528,Subscriber,1991,1,2020,11
21273,5272,49:31.9,17:24.3,3679,Bergen Ave,40.722104,-74.071455,3679,Bergen Ave,40.722104,-74.071455,14657,Customer,1990,1,2020,11
21274,222,56:52.8,00:34.9,3205,JC Medical Center,40.716540,-74.049638,3276,Marin Light Rail,40.714584,-74.042817,42601,Subscriber,1990,1,2020,11

In [19]:
df = pd.read_csv("Data/202010.csv")
df_extended = add_date(df,2020,10)
master_df = pd.concat([master_df,df_extended])
master_df.shape

(79416, 17)

In [20]:
for i in range(3,10):
    url = "Data/20200" + str(i) + ".csv";
    print(url);
    df = pd.read_csv(url)
    df_extended = add_date(df,2020,i)
    master_df = pd.concat([master_df,df_extended])
    print(master_df.shape)
    i+=1

Data/202003.csv
(97135, 17)
Data/202004.csv
(106403, 17)
Data/202005.csv
(131480, 17)
Data/202006.csv
(168401, 17)
Data/202007.csv
(207081, 17)
Data/202008.csv
(250348, 17)
Data/202009.csv
(304181, 17)

In [21]:
master_df.drop_duplicates()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Year,Month
0,588,42:51.9,52:40.4,3185,City Hall,40.717733,-74.043845,3269,Brunswick & 6th,40.726012,-74.050389,42596,Subscriber,1986,2,2021,2
1,454,29:25.6,37:00.1,3679,Bergen Ave,40.722104,-74.071455,3195,Sip Ave,40.730897,-74.063913,30360,Subscriber,1963,1,2021,2
2,1893,27:44.7,59:18.6,3211,Newark Ave,40.721525,-74.046305,3267,Morris Canal,40.712419,-74.038526,47254,Subscriber,1961,2,2021,2
3,874,42:55.8,57:30.1,3267,Morris Canal,40.712419,-74.038526,3199,Newport Pkwy,40.728745,-74.032108,48753,Subscriber,1991,1,2021,2
4,266,26:47.3,31:13.7,3276,Marin Light Rail,40.714584,-74.042817,3205,JC Medical Center,40.716540,-74.049638,32526,Subscriber,1987,1,2021,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53828,270,05:35.1,10:05.3,3207,Oakland Ave,40.737604,-74.052478,3640,Journal Square,40.733670,-74.062500,44744,Subscriber,1963,2,2020,9
53829,400,09:03.5,15:44.0,3209,Brunswick St,40.724176,-74.050656,3209,Brunswick St,40.724176,-74.050656,45345,Subscriber,1984,1,2020,9
53830,206,11:34.3,15:00.5,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,47019,Subscriber,1993,1,2020,9
53831,216,11:49.2,15:25.7,3195,Sip Ave,40.730897,-74.063913,3225,Baldwin at Montgomery,40.723659,-74.064194,42191,Subscriber,1966,1,2020,9
53832,418,12:31.8,19:30.5,3267,Morris Canal,40.712419,-74.038526,3186,Grove St PATH,40.719586,-74.043117,47255,Subscriber,1991,1,2020,9

In [22]:
master_df.to_csv("Data/CoronaYear.csv")

# Create data set for year prior to Corona Virus (March 2019 - Feb 2020)

In [27]:
url = ""
df = []
df_extended = []
master_df = []

for i in range(3,13):
    url = "Data/2019" + str(i) + ".csv";
    print(url);
    df = pd.read_csv(url)
    df_extended = add_date(df,2019,i)
    if i > 3:
        master_df = pd.concat([master_df,df_extended])
    elif i == 3:
        master_df = df_extended
    print(master_df.shape)
    i+=1

i = 1
for i in range(1,3):
    url = "Data/20200" + str(i) + ".csv";
    print(url);
    df = pd.read_csv(url)
    df_extended = add_date(df,2020,i)
    master_df = pd.concat([master_df,df_extended])
    print(master_df.shape)
    i+=1

Data/20193.csv
(23606, 17)
Data/20194.csv
(56662, 17)
Data/20195.csv
(92797, 17)
Data/20196.csv
(132227, 17)
Data/20197.csv
(175973, 17)
Data/20198.csv
(224684, 17)
Data/20199.csv
(273928, 17)
Data/201910.csv
(316181, 17)
Data/201911.csv
(346978, 17)
Data/201912.csv
(366706, 17)
Data/202001.csv
(392726, 17)
Data/202002.csv
(415688, 17)

In [28]:
master_df.to_csv("Data/PreCoronaYear.csv")